"""empty message

Revision ID: 30155c8d1a77
Revises: e026bacf3b15
Create Date: 2020-09-20 19:43:48.378931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30155c8d1a77'
down_revision = 'e026bacf3b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bground', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bground')
    # ### end Alembic commands ###
